### ISSUE TITLE
Add a statistics table for IP addresses on the "Network" page of the performance test report

### ISSUE THREAD

**Issue by xc-rvogel** [Xceptance/XLT#108]
Add an additional statistics table "IP Addresses" on the "Network" page of the performance test report. This table should list the IP addresses of the system under test similar to the "Hosts" table. The columns should be "IP Address", "Count", and "Percentage". If possible, the domain name that had been resolved to the respective IP address could also be listed there in a separate column.

This would help, for example, to evaluate the behavior of certain CDN environments.

**Comment by js-xc** [comment]
Once the changes to XLT are rolled out we should also document that there is a new field in result data - prepared in branch buildpath-and-result-data, see link.
