### ISSUE TITLE
Add transaction errors to "Agents" report page

### ISSUE THREAD

**Issue by xc-rvogel** [Xceptance/XLT#119]
In the current XLT reports, it cannot be distinguished if errors occur only for certain agents. Please add information about transaction errors per agent to the XLT reports.

Reasons for such agent-specific problems may be, for example, that a CDN limits traffic from certain locations or source IP addresses, defective agent machines, configuration problems, network problems, or incorrect IP whitelisting of single agent IPs.

To save calculation time and space, it may be sufficient to add two columns to the agent table (transaction error total, transaction error percentage) instead of adding charts. If these numbers are not zero, they should be shown in red color.

**Comment by jowerner** [comment]
After discussing this with the reporters, we also show the total number of transactions.
