### ISSUE TITLE
Update log4j dependency

### ISSUE THREAD

**Issue by DerNamenlose** [Xceptance/XLT#125]
Version 1 of log4j has not received support in a long time. XLT should update to a supported version in order to avoid issues due to vulnerabilities.

**Comment by rschwietzke** [comment]
This is on the list without an ETA due to the log4j 2.X issue stream, even though we don't use 2.X it but also have a non-updateable 1.X in the mix.

**Comment by rschwietzke** [comment]
See #182. Closing this one for now.
