### ISSUE TITLE
Search default Gradle build path for classes on agent controller

### ISSUE THREAD

**Issue by twoversionsofme** [Xceptance/XLT#19]
The default classpath set in `agentcontroller.sh` doesn't include the default Gradle build path.

[Gradle](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html) project (and [Maven](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) it seems) have default source directories of src/main/java.  Gradle then compiles classes to build/classes/java/main.  It would be helpful to include this in the path that the Agent Controller searches for test classes.

Current workaround I'm using is an action in one of my tasks to copy the class files to the default Maven build directory:
```    
    // copy classes from buildDir/classes/java/main/ to projectDir/target/classes/
    doLast {
        copy {
            from "$buildDir/classes/java/main"
            into "$projectDir/target/classes"
        }
    }
```

**Comment by jowerner** [comment]
Adding the standard Gradle classes directories to the class path should be an easy thing to do. I will update `agent.sh` and `agent.cmd` accordingly.

I wonder if we also have to add a new library directory to the class path. Does Gradle define a default directory where dependencies are copied to? In Maven, for example, that would be "target/dependency".

**Comment by twoversionsofme** [comment]
_Qualifier:_ I am a Gradle novice.
I believe that gradle downloads dependencies to the dependency cache which isn't under the project directory.  This is typically ~/.gradle/caches I believe.  See the link below:
 https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_cache

As a workaround I was copying the implementation level dependencies to the Maven dependency location with the below task:
```
task copyRuntimeLibs(type: Copy) {
    from configurations.implementation
    info "$projectDir/target/dependency"
  }
```

**Comment by jowerner** [comment]
All right, so let's start with the two classes directories. We can add a new library directory anytime if needed. Thanks for your help!
