### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#22]
Several XLT dependencies are available in a newer version.

**Comment by jowerner** [comment]
Updated most of the outdated compile/runtime dependencies, except:

* tyrus 1.16 -> pulls dependencies that are more dated than before
* dnsjava 3.x -> may require code changes (see #24)

Exclusion rules have been updated as well.

**Comment by h-arlt** [comment]
Found some updates for the following dependencies:
* aws-sdk-java-ec2 1.11.762
* xstream 1.4.12

Test deps:
* archunit-junit4 0.13.1
* pmd-java 5.8.1 (latest is 6.22.0 which is potentially incompatible)
* checkstyle 6.19 (latest is 8.31 which is potentially incompatible)

The used mocking frameworks also have some new versions but updating them should be done very carefully. This might be part of a separate issue.

**Comment by jowerner** [comment]
Done. I also adjusted the configuration of Checkstyle and PMD to get them working again.

The mocking libs we will update in #28 as the transition to Mockito 2.x requires some code changes.

**Comment by h-arlt** [comment]
I noticed that there are several `asm*` artifacts that don't have the same version. It seems that it does not cause any problems right now but I don't have a good feeling as I did not test all functionalities thoroughly.

I was able to unify all `asm*` artifacts to version 7.1 by removing `asm-commons` (not needed at all) and updating `parboiled-java` (dependency of pegdown). 
See PR #29.

**Comment by jowerner** [comment]
Our latest `asm` updates break the Cobertura coverage report ...
