### ISSUE TITLE
Add Apache license header to source files

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#23]
All XLT Java source files should carry a proper Apache license header.

**Comment by jowerner** [comment]
Added the license header to all Java source files with the help of `license-maven-plugin`.

Usage:

```
mvn license:format               # update the header
mvn license:check                # check if some files miss the header
```

Note that source files with an own license header have been excluded.

**Comment by h-arlt** [comment]
The maven plugin ships with a bunch of license templates - including Apache 2 - with proper placeholders that can be used right away. I'd prefer to use the template instead of a self-managed license file that has to be updated every year.

**Comment by jowerner** [comment]
I didn't use the template that ships with the plugin for two reasons:

* The template does not provide the ability to express a time range in the copyright, e.g. "2004-2020". It supports just "2004".
* Having full control of copyright and license text and formatting is a benefit.

**Comment by h-arlt** [comment]
AFAIK the copyright text is just a property which can take any string value.

As for the 2nd reason: this might be true for closed source. For open source software, it's absolutely okay to rely on other open source software to its job well. 
The shipped template looks absolutely fine to me and even if it is going to change, there is still the option to pin it to the working version or even to swall the bitter pill and use an individual template.

**Comment by h-arlt** [comment]
My previous comment describes only my personal point of view, of course ;-)

**Comment by jowerner** [comment]
Here is what the copyright section looks like in the template:

```
Copyright © ${project.inceptionYear} ${owner} (${email})
```

The copyright year will resolve to the value of `<inceptionYear>` in the pom.xml, in our case "2005".  Of course I could change that setting to `<inceptionYear>2005-2020</inceptionYear>` to achieve the wanted result but this feels simply wrong. Furthermore, there is nothing in the License Terms that requires specifying an email address in the copyright.

So having an own license header file is inevitable.

If you feel better if we would templatize that file and feed it with parameters from the pom.xml instead of adjusting the file directly, we can of course do so.

**Comment by h-arlt** [comment]
Ok. Got your point.

My suggestion to template the license file origins from the idea that such common project global information like the copyright is managed in the POM file and passed the template. This might also reduce the risk of a malformed license file due to manual adjustments.

**Comment by jowerner** [comment]
Done. Not sure why the commit is not linked automatically to this issue. See: https://github.com/Xceptance/XLT/commit/8588a0862ff7ff2f99d67a0892bf3d85a4f2d0f3

**Comment by h-arlt** [comment]
Nice. Thanks
