### ISSUE TITLE
Crosshair for easier data visualization

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#271]
Add to all charts a crosshair (small and transparent but still visible) to hover over the chart and be able to easily read X and X-axis. Example: https://eschmann.dev/crosshair.js/

It should not display any values from the chart, just help to more accurately related to X and Y axis.

**Comment by rschwietzke** [comment]
That would be nice. Runtime value is likely enough, time is still okish to see.

**Comment by jowerner** [comment]
This would require metadata to be saved alongside each chart image, i.e. for each sub-chart: size and position, time range, value range. May take some time. The original idea of just providing a crosshair as a visual aid (full image, no values) can be done more quickly.

**Comment by rschwietzke** [comment]
Ok, let's do a crosshair to allow more easily to read time and value, don't do any values.
