### ISSUE TITLE
Remove script-doc generator

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#275]
Any existing test suite with XML-based script test cases should now have been migrated to Java. Time to remove the script-doc generator that creates HTML docs from script test cases.

**Comment by h-arlt** [comment]
> Any existing test suite with XML-based script test cases should now have been migrated to Java.
Then we can also drop support for interpreting XML script testcases, right?

**Comment by jowerner** [comment]
There are still users with XML-based test cases, so we have to keep that functionality. Then we better also keep the script-doc generator.
