### ISSUE TITLE
Move summary chart above data tables

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#291]
To make the summary chart more easily accessible, especially when the tables (requests) are very long, we should move the Summary section with the chart above the table with all details. The individual charts stay under the table. 

![image](https://user-images.githubusercontent.com/1793856/207003722-d4b19381-e1e8-4e80-9e47-fd5e4f291843.png)

**Comment by js-xc** [comment]
While I appreciate this as a learning experience I wonder whether the change will be useful for load testers. I understand that it might be valuable for non-tech users to see the overview graphic first, but for evaluating the report I usually need the data tables more often.

**Comment by rschwietzke** [comment]
It is about seeing potential problems early and because we share that with customers, they should see that first. Additionally, very long tables take long to load and so the chart is already there.
