### ISSUE TITLE
Binary PUT/POST support HttpRequest

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#33]
The HttpRequest supports only String aka non-binary or base64 data right now (because also the underlying WebClient by HtmlUnit only supports that), but there is a need for binary upload, such as images. S3 buckets are such an use case.

**Comment by jowerner** [comment]
Overloaded the `body(String)` method with variants that take other parameter types:

1. `body(byte[])`
2. `body(File)`
3. `body(InputStream)`

Only the first overload is actually needed, but added the other two for convenience. Please note that the content of the file or input stream will be buffered in memory. A streaming mode for huge data is not supported yet.

See below for some example code how to put the content of a binary file into the body of a PUT request:

```
HttpRequest httpRequest = new HttpRequest();
httpRequest.timerName("Upload");
httpRequest.baseUrl(UPLOAD_URL);
httpRequest.method(HttpMethod.PUT);
httpRequest.header("Content-Type", "application/gzip");
httpRequest.body(new File("/tmp/123.tar.gz"));
```

**Comment by rschwietzke** [comment]
Ack on the API. Please document whether or not the Inputstream will be closed by the method or not.

**Comment by jowerner** [comment]
> Please document whether or not the Inputstream will be closed by the method or not.

Done.
