### ISSUE TITLE
Agent classpath doesn't support Kotlin

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#335]
When having Kotlin as the host language pulling in XLT Java and building it with Gradle, there seem to be `main/kotlin` subdirs we don't add to the classpath on the agent or don't upload at all. We should properly support the JVM language zoo when Maven or Gradle are used.

**Comment by js-xc** [comment]
Side task for this: check doc whether there's any info about which folders will be included in the agents' classpath, hence make the test work. We should document which folder structures/directories we support, as there might be quite some variety for different build tools/project languages etc.

**Comment by js-xc** [comment]
`agent.sh` looks like only gradle (`CP_GRD`) classpath is concerned here (`/build/classes/java/main`/`/build/classes/java/test`), mvn classpath is not language specific? I checked in a local project, same structure is applied to kotlin/scala:
*  `/build/classes/kotlin/main`/`/build/classes/kotlin/test`
*  `/build/classes/scala/main`/`/build/classes/scala/test`
Would this do the trick? (Task says `main/kotlin`, which isn't exactly what I see.)

**Comment by jowerner** [comment]
Maybe original poster meant `kotlin/main`. Please add just the Kotlin subdirs to the Gradle classpath. There is no demand for Scala support right now.
