### ISSUE TITLE
Ensure right-sizing of charts in the HTML/CSS by setting the dimensions

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#361]
To avoid flickering when chart-tabs are used, we have to set the size in the HTML (via CSS). Because this is a dynamic and comes from `com.xceptance.xlt.reportgenerator.charts.width` and `com.xceptance.xlt.reportgenerator.charts.height`, we have to get these attributes into the report XML. This enables us to dynamically apply these in the generated HTML, likely by an inline CSS to avoid  that we add a style or size to everything chart images.

**Comment by js-xc** [comment]
Current state of branch contains css snippet in html head, which locally seems to remove the flickering. Is this sufficient or do you prefer width and height as html attributes on the chart images?
