### ISSUE TITLE
Security: Update jQuery and dependencies for reports

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#364]
Update jQuery and its dependencies for the reports to the latest secure version. At the time of the writing, it is v3.6.4. Make sure we use the minified version.

**Comment by js-xc** [comment]
Do you consider jQuery.scrollTo/jQuery.hoverIntent dependencies? Anyway neither has released a new version in the past 2 years, we could update hoverIntent but not sure whether we need to.

**Comment by rschwietzke** [comment]
> Do you consider jQuery.scrollTo/jQuery.hoverIntent dependencies? Anyway neither has released a new version in the past 2 years, we could update hoverIntent but not sure whether we need to.
These depend on jQuery, hence these are dependencies and must match jQuery or at least stay compatible. If they don't have new version, fine, but we have to test that things still work okish. If there is a latest, please use it but test the functionality.

**Comment by js-xc** [comment]
Do you have an idea what these are supposed to _do_, functionally? I don't even know how I'd see they're not working.

**Comment by rschwietzke** [comment]
> Do you have an idea what these are supposed to _do_, functionally? I don't even know how I'd see they're not working.

scrollTo does the soft scrolling to charts when you click on names or the scrollback to top when clicking the header menu including the back to table links.

hoverIntent brings up the 10 url examples when hovering over a request name.
