### ISSUE TITLE
Update Documentation because Posters Will Not Be Shipped Anymore

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#408]
Please update https://docs.xceptance.com/xlt/load-testing/quick-start/20-demo-application/ to explain how to get Posters and run it. The new XLT versions will no longer ship it. See: https://github.com/Xceptance/posters-demo-store
You can also just borrow much of the content, if needed.

**Comment by js-xc** [comment]
update is ready but I'd wait with the merge until the maven link for the store actually works (or it moves elsewhere)
