### ISSUE TITLE
FastHashMap class documentations

### ISSUE THREAD

**Issue by rbri** [Xceptance/XLT#428]
The class src/main/java/com/xceptance/common/collection/FastHashMap.java looks really interesting but there is no real information in the class comment why someone should use this in favor of the java one.
Any chance to add some words about the idea, the pro/cons and maybe also what 'fast' means here.

**Comment by rschwietzke** [comment]
Sure. Will do. Bottom line: It uses less memory, has less cache misses due to direct value storage, and due to less code, is easier inlineable by the JIT.

**Comment by rschwietzke** [comment]
Copied to Neko and improved.
