### ISSUE TITLE
Extend Comparison Reports to cover additional metrics 

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#429]
Extend the comparison reports to also include the PXX metrics, distinct count (requests), and bandwidth (requests). Because requests do no longer feature 1/d, we should remove that from the comparison as well (it is still in the XML data, but not displayed).

**Comment by js-xc** [comment]
1/min is everywhere in comparison report, but nowhere in standard load report. Do you mean we should also unify standard/comparison report by adding 1/min everywhere in the standard report?
