### ISSUE TITLE
Page Load Timings no longer reported to Graphite

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#43]
In older versions of XLT, page load timing data were reported as custom timers to Graphite. However, in the latest version these values do no longer appear in Graphite.

**Comment by jowerner** [comment]
The metrics reporter still reports custom timers to Graphite. But a while ago (XLT 4.12.0), we introduced a dedicated data class `PageLoadTimingData` to store page load timing measurements. We need to extend the metrics reporter to report this new type of data as well.

**Comment by jowerner** [comment]
Now page load timing data is sent to Graphite again, but note that this data is no longer stored to the "custom" subtrees, but to the "pageLoadTimings" subtrees. The bucket name structure for both specific page load timing records and summary records is similar to that of actions and custom timers. See below for an example how page load timing data is reported to Graphite:

```
xlt.Posters.ac001.pageLoadTimings.Homepage__FirstContentfulPaint_.errors 0 1592575693
xlt.Posters.ac001.pageLoadTimings.Homepage__FirstContentfulPaint_.runtime.max 543 1592575693
xlt.Posters.ac001.pageLoadTimings.Homepage__FirstContentfulPaint_.runtime.mean 543.00 1592575693
xlt.Posters.ac001.pageLoadTimings.Homepage__FirstContentfulPaint_.runtime.min 543 1592575693
...
xlt.Posters.ac001.summary.pageLoadTimings.count 18 1592575693
xlt.Posters.ac001.summary.pageLoadTimings.errors 0 1592575693
xlt.Posters.ac001.summary.pageLoadTimings.runtime.max 543 1592575693
xlt.Posters.ac001.summary.pageLoadTimings.runtime.mean 270.17 1592575693
xlt.Posters.ac001.summary.pageLoadTimings.runtime.min 20 1592575693
```

**Comment by ckeiner** [comment]
Seems fine to me.
