### ISSUE TITLE
Control HtmlEndTag and ContentLength validators by property

### ISSUE THREAD

**Issue by m-ullrich** [Xceptance/XLT#441]
It should be possible to enable/disable the `HtmlEndTagValidator` and `ContentLengthValidator` by property, similar to `XHTMLValidator`.

**Comment by rschwietzke** [comment]
They should be disabled by default.

**Comment by m-ullrich** [comment]
In discussion with @rschwietzke it was decided to not control the validators in XLT via property but do in the test suites instead. At the same time this requires removing the existing property control from XHTMLValidator.
