### ISSUE TITLE
Comparison report: Split the single page into multiple pages

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#447]
Currently, the comparison report is just one long page. Similar to the load test report, we should split this page into several smaller pages. The navigation would remain the same, but would point to the new sub-pages.

**Comment by js-xc** [comment]
While I'm at it, should we also update trend report? This is split already, with the exception of overview, which is on the same page as transactions. In the one I just generated there seems to be nothing in it and the Overview section is therefore a little short, but still I think it's weird design to put this on another page while everything else got its own.
