### ISSUE TITLE
Responsive Result Browser

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#465]
For the purpose of monitoring, we sometimes require a mobile/responsive view to quickly check in whether a certain notification is worse following up. 

Create a prototype of a responsive result browser which might have fewer features but still enables one to quickly check on the most important data even though some things might be quirky on a mobile UI. We talk about a smartphone here, not about a tablet. 

The left navigation should be hidden and can be opened and closed manually. The overall size must be bigger to make it accessible. The right detail part must be zoomable, especially when we present just screenshots. The details for requests must be larger, not sure if this requires changing the ordering (columns to rows).

**Comment by jowerner** [comment]
See also #406.

**Comment by js-xc** [comment]
Feel free to comment on current state of branch. Changes so far:
* menu items got bigger on mobile
* for mobile in portrait mode: row layout for menu and content, menu slider is gone, instead the menu can roll up and down (by expand icon in header, which I would prefer to replace by the hamburger menu item and use a filter icon for the filter menu instead, but in any case I have a feeling nobody notices or wants to use the expander icon for this, better ideas?)
* if the action content is a screenshot (real browser tests) it can be switched between 100% size and fit width to available width on screen (not ideal, see point above) by button down right
* style for request/reponse info tabs and beautify/highlight/select all buttons changed a bit to fit less space/new layout

Currently checking what we could do with swipe gestures here, but there's a lot of functionality in the reports and gestures might be ambiguous, too.
