### ISSUE TITLE
Output error percentage values as part of the XML data output

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#474]
Enhance the testreport.xml in a way that the percentage values are also in the XML instead of being calculated as part of the HTML rendering. In the example below, we are looking for the error percentage.

![image](https://github.com/Xceptance/XLT/assets/1793856/b8b1f2df-a95f-49a1-940b-4b731c3224a6)

**Comment by js-xc** [comment]
Is this enhancement exclusively about the error percentages on the timers or do you want to get rid of the complete percentage calculation during rendering, i.e. also in request runtime segmentation and agent transaction errors?
