### ISSUE TITLE
Invalid characters break XML transformation

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#50]
Invalid characters in the data input such as error messages might lead to incorrect XML that breaks the transformation. In this case it was a \0 .

```
Transforming XML data file '20200813-161124/testreport.xml' ...
file:20200813-161124/testreport.xml; Line #23399; Column #86; Character reference "&#x0" is an invalid XML character.
```

That might be the utility to use https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeXml10-java.lang.String-

**Comment by jowerner** [comment]
Characters not valid according the XML 1.0 specification will now be silently removed.
