### ISSUE TITLE
RegEx "negative lookahead" within XPath in scorecard

### ISSUE THREAD

**Issue by roederXC** [Xceptance/XLT#515]
The regex "negative lookahead" does not work within an XPath in the scorecard-config.JSON

For example, if you use this expression as a rule selector:
`"sum(//transactions/transaction[matches(name, '^(?!.*Crawler).+$')]/count)"`
you will get this Error in the Report/Scorecard:
`Error evaluating rule 'visitsWithoutCrawlerCheck': [Check #0] Syntax error at char 2 in regular expression: No expression before quantifier. Found while atomizing the first argument of fn:sum() in {docOrder(((root/descendant::transactions)/transaction[fn:matches(...)])/count)} on line 1`

To better reproduce and handle the issue, I am attaching my debug-scorecard-config.json.
[debug-scorecard-config.json](https://github.com/user-attachments/files/16460731/debug-scorecard-config.json)

**Comment by h-arlt** [comment]
Regular expressions in XPath do **not** support lookahead or lookbehind constructs. That's why it is reported as being erroneous.

See [here](https://www.w3.org/TR/xpath-functions/#regex-syntax) for details on what regular expression syntax in XPath 3.1.

**Comment by h-arlt** [comment]
As workaround, you may simply substract the sum of all transaction counts whose names contains `TCrawler` from the total sum of all transactions: `sum(//transactions/transaction/count)-sum(//transactions/transaction[contains(name, 'Crawler')]/count)`

**Comment by rschwietzke** [comment]
With #508 we will get a way to deal with that more easily because we label things upfront and make the queries for the scorecard simpler.

**Comment by roederXC** [comment]
@h-arlt 
Maybe the better workauround is to use only XPath:
`"sum(//transactions/transaction[not(contains(name, 'Crawler'))]/count)"``

But maybe it is still be an known or ongoing issue to us a "?" in ExPath here.

**Comment by rschwietzke** [comment]
This page explocitly says, that negative lookahead is purposly not part of the spec:
https://www.web3d.org/specifications/X3dRegularExpressions.html

> [Negative Lookahead](https://www.regular-expressions.info/lookaround.html) filters have potential to disqualify attributes that contain illegal values.
> 
> [W3C Recommendation for XML Schema (XSD): Regular Expressions](https://www.w3.org/TR/xmlschema11-2/#regexs) does not support this construct, perhaps to avoid the possibility of computational denial-of-service (DoS) attacks.
