### ISSUE TITLE
Incorrect Protocol in Result Browser Listed

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#53]
When running a full browser test (Chrome) and checking the result browser later, the response indicates always:

```
 Status	200 - HTTP/1.1 200
```
which is not correct, because in many cases it is H2 nowadays and this also is listed when we connect against H2 hosts.

**Comment by h-arlt** [comment]
This is a known issue and caused by the fact that our extension used to measure client performance metrics is not able detect the used HTTP version at all. The HTTP headers necessary to do so are not available via WebExtension API. Unless this is fixed - don't know if it is yet - this issue is unlikely to be fixed.

**Comment by jowerner** [comment]
When visiting https://www.google.de/, different values for the `statusLine` property are passed to our measurement extensions depending on the browser:

* Chrome -> HTTP/1.1 200
* Firefox -> HTTP/2.0 200 OK

For unknown reasons, Chrome passes "HTTP/1.1" although the missing status message ("OK") and also the response headers indicate an HTTP/2 response. There is not much we can do about that.

However, the fact that the result browser shows "200 - HTTP/1.1 200" is a side effect of our extension code not expecting a missing status message. This we can fix, I believe. The result browser would then show "200 - OK" if there was a status message and "200 - n/a" if there wasn't.

**Comment by jowerner** [comment]
Our extensions now return `null` for the status message in case there was none in the data passed by the browser. Furthermore, the regex that parses the status message from the status line is more robust now and would accept protocol versions without a minor version, such as "HTTP/2", as well.

**Comment by h-arlt** [comment]
That's all we can do at the moment.
