### ISSUE TITLE
Allow media type parameters

### ISSUE THREAD

**Issue by jensvoss0253** [Xceptance/XLT#60]
In some cases, an HTTP response sends a Content-Type header of the form
> application/hal+json;charset=utf8;profile="https://my.api.com/";version=1

which knocks out the `com.xceptance.xlt.api.htmlunit.LightWeightPage.determineContentCharset()` method since it considers everything after the "charset=" to be an encoding name.

One obvious fix to this problem would be to replace the relevant line in the above method by
> `String charsetName = StringUtils.substringBetween(response.getResponseHeaderValue("content-type") + ";", "charset=", ";");`

alternatively, one could use a simple regex pattern.

**Comment by jowerner** [comment]
Thanks for reporting this issue and also for your analysis! Should be fixed now. We will release XLT 5.2.1 in the next days.
