### ISSUE TITLE
Enable HttpRequest for file uploads

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#74]
Currently, it is not possible to upload files as multi-part form data with the HttpRequest class. The reason is that HttpRequest treats parameters as name/value pairs only, but for file uploads we need support for key/data pairs.

**Comment by jowerner** [comment]
Now HttpRequest supports `KeyDataPair` parameters as well. See below for some example code how to upload a file:

```
HttpRequest httpRequest = new HttpRequest();
httpRequest.timerName("Upload");
httpRequest.baseUrl(UPLOAD_URL);
httpRequest.method(HttpMethod.POST);
httpRequest.encodingType(FormEncodingType.MULTIPART);
httpRequest.param(new KeyDataPair("file", "/tmp/123.tar.gz", null, "application/gzip", StandardCharsets.UTF_8));

httpRequest.fire();
```

**Comment by rschwietzke** [comment]
Can I suggest an additional convince method KeyDataPair.of() to make the code a little smaller and run a more typical Java 11 style?! What is the `null` for?

**Comment by h-arlt** [comment]
Please note that `KeyValuePair` and `KeyDataPair` are classes provided by HtmlUnit.

**Comment by jowerner** [comment]
Strictly speaking, KeyDataPair is not our code. The 3rd parameter is an (optional) custom file name. If null the name will be taken from the input file ("123.tar.gz").

**Comment by rschwietzke** [comment]
Ok, if this is not our code, we go without the convenience method.
