### ISSUE TITLE
XLT error charts seem to miss support for Japanese characters

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/XLT#78]
During a project for a Japanese site, we got Japanese error messages. These are listed fine in the tables, but the charts miss a header (see screenshot below).

![missingChartHeadline](https://user-images.githubusercontent.com/2975211/108377905-c8d88200-7204-11eb-938a-481045fc5a4e.jpg)

**Comment by h-arlt** [comment]
The reason for the observed behavior is that Roboto - the font used by XLT for chart generation - lacks support for Chinese or Japanese symbols (https://github.com/podlove/podlove-subscribe-button/issues/110).

Unfortunately, there is no font available, that covers nearly all known regions/languages. This means that even switching the font doesn't solve the problem of potentially missing symbols.

**Comment by rschwietzke** [comment]
Closed as won't be fixed. Users are free to edit the XSL/CSS files which refer to the font and include a suitable one if required.
